# Generated by Django 4.2.6 on 2023-10-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
